powerData <- read.table("./household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
powerData$DateTime <- paste(powerData$Date, powerData$Time)
powerData$DateTime <- strptime(powerData$DateTime, "%d/%m/%Y %H:%M:%S")
dataSet <- subset(powerData, DateTime >= as.POSIXct("2007-02-01 00:00:00") & DateTime < as.POSIXct("2007-02-03 00:00:00"))
par(mfrow = c (2,2))
plot(dataSet$DateTime, dataSet$Global_active_power, type = "l")
plot(dataSet$DateTime, dataSet$Voltage, type = "l")
plot(dataSet$DateTime, dataSet$Sub_metering_1, type = "l", col = "black")
lines(dataSet$DateTime, dataSet$Sub_metering_2, type = "l", col = "red")
lines(dataSet$DateTime, dataSet$Sub_metering_3, type = "l", col = "blue")
plot(dataSet$DateTime, dataSet$Global_reactive_power, type = "l")
